[features]
seeds = false
skip-lint = false
[programs.localnet]
airdrop_program = "52ThXWX6Syd6ahz57FyBxJvoh6hf1HvWFTTDwWT5nNzw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chris/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
